### ISSUE TITLE
Public control-plane subnet is not accessible from internet

### ISSUE THREAD

**Issue by mailbox171** [oracle-terraform-modules/terraform-oci-oke#473]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.1.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/oci v4.63.0
+ provider registry.terraform.io/hashicorp/time v0.7.2

module "oke" {
  source                                =   "oracle-terraform-modules/oke/oci"
  version                               =   "4.0.0"
...

### Affected Resource(s)

control plane subnet

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Expected Behavior

The control plane subnet of a public OKE cluster should have port 6443 open.
This was the case with version 3.

### Actual Behavior

The only sec list rule provisioned allow access from internal (private) addresses only

No | 10.0.0.16/29 | TCP | All | 6443 |   | TCP traffic for ports: 6443
 

 

### Steps to Reproduce

1. `terraform apply`

**Comment by karthicgit** [comment]
Could you please use latest version and let us know still the issue persist.

**Comment by mailbox171** [comment]
Hello,
I am not cloning the repo.

Can you please tell me what should I set to use the latest?

  module "oke" {
   source = "oracle-terraform-modules/oke/oci"
   version = "?.?.?"
   ...

Thanks a lot

**Comment by karthicgit** [comment]
@mailbox171 4.1.4 is the latest version.

**Comment by karthicgit** [comment]
@mailbox171 Thanks for reporting I have raised a issue for it . We will fix it asap.

**Comment by hyder** [comment]
@mailbox171: it looks like you using the module remotely. We've fixed and release a patch: v4.1.5. Please use this instead.

**Comment by hyder** [comment]
I've tested with v4.1.5 and setting the `control_plane_type           = "public"`. It works fine

**Comment by mailbox171** [comment]
Testing ith v4.1.5 I still have the same issue.
Maybe I am doing something wrong.
I have a public endpoint created for the cluster. But the control-plane subnet only has one seclist allowing access from 10.0.0.16/29.
Adding a seclist from 0.0.0.0/0 to port 6443 solves the problem

**Comment by hyder** [comment]
> Testing ith v4.1.5 I still have the same issue.
> Maybe I am doing something wrong.
> I have a public endpoint created for the cluster. But the control-plane subnet only has one seclist allowing access from 10.0.0.16/29.
> Adding a seclist from 0.0.0.0/0 to port 6443 solves the problem

The same rule should exist in the control plane NSG. Can you verify that please?

**Comment by mailbox171** [comment]
I have only these 2 NSGs


Direction:
 Ingress
Stateless:
 No
	
Source Type:
 CIDR
Source:
 10.0.64.0/18
	TCP	
Source Port Range:
 All
Destination Port Range:
 6443
Allow:
 TCP tra...
Allow worker nodes to control plane API endpoint communication	
1BF721

----------------------------------------------------


Direction:
 Ingress
Stateless:
 No
	
Source Type:
 CIDR
Source:
 10.0.0.8/29
	TCP	
Source Port Range:
 All
Destination Port Range:
 6443
Allow:
 TCP tra...
Allow operator host access to control plane. Required for kubectl/helm...
C22167

**Comment by hyder** [comment]
Can you please name the NSGs?

**Comment by mailbox171** [comment]
I see they have a description that identifies them clearly-
What do you mean by "names"?

**Comment by hyder** [comment]
The display names of the nsgs in the VCN

**Comment by mailbox171** [comment]
I have 4 NSGs

NSG: odadev-control-plane
Inside there are various rules, including the two rules I reported above

Other 3 NSGs: operator, workers, pub-lb

**Comment by hyder** [comment]
Like I said, if you set `control_plane_type = "public"`, you should be able to access it.

**Comment by mailbox171** [comment]
I can only tell you what I see.
--------------------------------
I set control_plane-type = public
run terraform
control plane provisioned in public subnet
endpoint with private and public IP (port 6443)
access from internet hangs
The only 2 Ingress rules I have to port 6443  mention "private" CIDRs sources (see above)
I add one neww rule to port 6443 with source 0.0.0.0/0 in NSG control-plane
kubectl works

**Comment by mailbox171** [comment]
Setting "control_plane_allowed_cidrs" solved the problem.

Thank you
